//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GuitarShop : DbContext
    {
        public GuitarShop()
            : base("name=GuitarShop")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<guitar> guitar { get; set; }
        public virtual DbSet<guitar_category> guitar_category { get; set; }
        public virtual DbSet<guitar_supplier> guitar_supplier { get; set; }
        public virtual DbSet<guitar_warehouse> guitar_warehouse { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<users_guitar> users_guitar { get; set; }
        public virtual DbSet<warehouse> warehouse { get; set; }
    }
}
