//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class guitar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public guitar()
        {
            this.guitar_supplier = new HashSet<guitar_supplier>();
            this.guitar_warehouse = new HashSet<guitar_warehouse>();
            this.users_guitar = new HashSet<users_guitar>();
        }
    
        public int id_guitar { get; set; }
        public string Name { get; set; }
        public Nullable<int> Cost { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> id_category { get; set; }
    
        public virtual guitar_category guitar_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guitar_supplier> guitar_supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guitar_warehouse> guitar_warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users_guitar> users_guitar { get; set; }
    }
}
