//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class guitar_supplier
    {
        public int id_guitar { get; set; }
        public int id_supplier { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual guitar guitar { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
